import { SequencerData, ProcessStepData } from './types';

export const SEQUENCERS: SequencerData[] = [
  {
    id: 'uniseq100',
    name: 'UniSeq100',
    imageSrc: 'images/uniseq100.png',
    imageAlt: 'UniSeq100',
    subtitle: 'Компактный секвенатор для лабораторий с малым и средним потоком образцов',
    specs: [
      { label: 'Производительность:', value: '10 млн прочтений' },
      { label: 'Длина прочтения:', value: 'SE50/75/100/150, PE50/75/100/150' },
      { label: 'Качество данных:', value: 'Q30 ≥ 90%' },
      { label: 'Время секвенирования:', value: '7-16 часов' },
      { label: 'Размеры:', value: '600×290×630 мм' },
      { label: 'Площадь:', value: '< 0.2 м²' },
    ],
    idealFor: [
      'Лабораторий с малым и средним потоком образцов',
      'Таргетного секвенирования',
      'Запусков от 1 образца на ячейку',
      'Срочных исследований и получения результата на следующий день',
      'Экономии бюджета и минимизации стоимости реагентов на запуск',
      'Ограниченного пространства — настольное размещение < 0.2 м²',
    ],
  },
  {
    id: 'uniseq2000',
    name: 'UniSeq2000',
    imageSrc: 'images/uniseq2000.png',
    imageAlt: 'UniSeq2000',
    subtitle: 'Высокопроизводительная платформа для широкого спектра клинических применений',
    specs: [
      { label: 'Производительность:', value: '160 млн прочтений' },
      { label: 'Длина прочтения:', value: 'SE50/75/100/150, PE50/75/100' },
      { label: 'Качество данных:', value: 'Q30 > 90%' },
      { label: 'Время секвенирования:', value: '7-33 часов' },
      { label: 'Размеры:', value: '800×682×738 мм' },
      { label: 'Площадь:', value: '≈ 0,5 м²' },
    ],
    idealFor: [
      'Лабораторий со средним и большим потоком образцов',
      'Таргетного секвенирования',
      'Запусков от 10 образцов на ячейку',
      'Экономии бюджета и минимизации стоимости реагентов на запуск при среднем и большом потоке',
      'Универсальности — таргетное NGS, метагеномика, патогены, NIPT, CNV-seq, PGS, онкология',
    ],
  },
];

export const PROCESS_STEPS: ProcessStepData[] = [
  {
    number: 1,
    icon: '🧪',
    title: 'Система автоматического выделения',
    description: 'ДНК/РНК',
    imageSrc: 'images/nucleic_acid_extraction_system.png',
    imageAlt: 'Система выделения',
  },
  {
    number: 2,
    icon: '⚙️',
    title: 'Система автоматического дозирования',
    description: 'Роботизированная система с максимальным функционалом для NGS',
    imageSrc: 'images/Liquid_Handing_Workstation_v2.png',
    imageAlt: 'Система дозирования',
  },
  {
    number: 3,
    icon: '📊',
    title: 'Real-time ПЦР амплификаторы',
    description: 'Амплификация библиотек',
    imageSrc: 'images/PCR System.png',
    imageAlt: 'ПЦР система',
  },
  {
    number: 4,
    icon: '🔬',
    title: 'Системы детекции',
    description: 'Флюориметры и др.',
    imageSrc: 'images/QC.png',
    imageAlt: 'Системы детекции',
  },
  {
    number: 5,
    icon: '🧬',
    title: 'Автоматическая картриджная система приготовления библиотек',
    description: 'Внесение ДНК в предзаполненные картриджи и получение готовой библиотеки на выходе',
    imageSrc: 'images/UNIPre-1.jpg',
    imageAlt: 'Картриджная система',
  },
  {
    number: 6,
    icon: '🔭',
    title: 'Секвенаторы',
    description: 'UniSeq100 и UniSeq2000',
    imageSrc: 'images/uniseq100.png',
    imageAlt: 'Секвенаторы',
  },
  {
    number: 7,
    icon: '💻',
    title: 'Биоинформатическая станция',
    description: 'Готовые пайплайны, интеграция с биоинформатическими базами',
    imageSrc: 'images/BI.png',
    imageAlt: 'Биоинформатическая станция',
  },
];
